import { StudySpot } from './types';

export const MOCK_SPOTS: StudySpot[] = [
  {
    id: '1',
    name: 'Central Library - 4th Floor',
    type: 'Library',
    description: 'A dedicated silent study zone with individual cubicles. Perfect for deep focus sessions.',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80',
    noiseLevel: 'Quiet',
    crowdLevel: 'High',
    hasOutlets: true,
    hasFood: false,
    hasWifi: true,
    rating: 4.8,
    location: 'Main Quad',
    reviews: [
      {
        id: 'r1',
        userId: 'u1',
        userName: 'Alex Chen',
        rating: 5,
        comment: 'Dead silent. Exactly what I needed for finals.',
        date: '2023-10-15',
      },
    ],
  },
  {
    id: '2',
    name: 'The Bean Counters Cafe',
    type: 'Cafe',
    description: 'Bustling cafe with great espresso. Good for group work if you don\'t mind the background noise.',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    noiseLevel: 'Loud',
    crowdLevel: 'Medium',
    hasOutlets: true,
    hasFood: true,
    hasWifi: true,
    rating: 4.2,
    location: 'Student Union',
    reviews: [],
  },
  {
    id: '3',
    name: 'Engineering Quad Lawn',
    type: 'Outdoor',
    description: 'Open grass area with benches. Great for sunny days, but wifi can be spotty.',
    image: 'https://images.unsplash.com/photo-1565514020176-db792f392945?auto=format&fit=crop&w=800&q=80',
    noiseLevel: 'Moderate',
    crowdLevel: 'Low',
    hasOutlets: false,
    hasFood: false,
    hasWifi: false,
    rating: 3.9,
    location: 'North Campus',
    reviews: [],
  },
  {
    id: '4',
    name: 'Science Center Atrium',
    type: 'Common Area',
    description: 'Modern architecture with lots of natural light. Tables are large, good for groups.',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    noiseLevel: 'Moderate',
    crowdLevel: 'High',
    hasOutlets: true,
    hasFood: true,
    hasWifi: true,
    rating: 4.5,
    location: 'East Wing',
    reviews: [],
  },
  {
    id: '5',
    name: 'Old Stacks Basement',
    type: 'Library',
    description: 'Hidden gem. A bit creepy but absolutely zero distractions.',
    image: 'https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=800&q=80',
    noiseLevel: 'Quiet',
    crowdLevel: 'Low',
    hasOutlets: true,
    hasFood: false,
    hasWifi: true,
    rating: 4.0,
    location: 'Main Library',
    reviews: [],
  },
];